apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "kotaemon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kotaemon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kotaemon.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
          volumeMounts:
            - name: storage-volume
              mountPath: /storage
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
