apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "kotaemon.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}

