{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "kotaemon.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}
  port:
    targetPort: http
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
  {{- end }}
{{- end }}
