image:
  repository: hartree.azurecr.io/stardust/kotaemon
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: kotaemon

replicaCount: 1

storage:
  size: 20Gi
  storageClassName: ""  # Use cluster default

service:
  port: 80
  containerPort: 7860
  targetPort: 7860

resources:
  gpu: 1
  requests:
    cpu: 8
    memory: 8Gi
  limits:
    cpu: 16
    memory: 32Gi

route:
  enabled: true
  port: 80
  tls:
    enabled: true
    termination: edge
