image:
  repository: scheckley/kotaemon
  tag: latest
  pullPolicy: Always

replicaCount: 1

storage:
  size: 20Gi
  storageClassName: ""  # Use cluster default

service:
  port: 80
  containerPort: 7860
  targetPort: 7860

resources:
  requests:
    cpu: 16
    memory: 8Gi
  limits:
    cpu: 32
    memory: 32Gi

route:
  enabled: true
  port: 80
  tls:
    enabled: true
    termination: edge
